Publish to SNS
shuttleql/session-service pull request #4
Opened 2016-11-20 21:40 UTC by clemmy

2016-11-20 22:54 UTC, jasonf7 requested changes

2016-11-20 22:54 UTC, jasonf7 commented on src/main/scala/com/shuttleql/services/session/UserToSessionsDAO.scala
> +  def broadcastUserUpdate(): Unit = {
`broadcastCheckinUpdate`

2016-11-21 01:30 UTC, clemmy commented on src/main/scala/com/shuttleql/services/session/UserToSessionsDAO.scala
> +  def broadcastUserUpdate(): Unit = {
for now it's just a user update (I specify `users` as the resource)

2016-11-21 01:43 UTC, jasonf7 approved these changes

2016-11-21 02:08 UTC, merged